services:
  - type: web
    name: Easyspearfishing
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start

  - type: static
    name: easyspearfishing-web
    plan: free
    buildCommand: ""
    staticPublishPath: ./public
